config/routes.rb
Rails.application.routes.draw do
devise_for :users
root to: "homes#top"
get "/home/about" => "homes#about", as: "about"
resources :users, only: [:show, :edit, :create, :index, :update]
resources :books, only: [:new, :index, :show, :create, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
     user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
     root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
     @book = Book.new
  end
  def show
     @books = Book.find(params[:id])
     @user = @books.user
     @book = Book.new
  end

  def index
      @books = Book.all.order(id: :asc)
      @book = Book.new
      @user = current_user
  end

  def edit
     @book = Book.find(params[:id])
     unless @book.user.id == current_user.id
     redirect_to books_path
     end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
   else
    @books = Book.all.order(id: :asc)
    @user = current_user
    render :index
   end
  end

  def update
     @book = Book.find(params[:id])
     unless @book.user.id == current_user.id
     redirect_to books_path
     end
     if @book.update(book_params)
     flash[:notice] = "Book was successfully updated."
     redirect_to book_path(@book.id)
     else
     @books = Book.all.order(id: :asc)
     render :edit
     end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :image, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = User.find(params[:id])
     @books = @user.books
     @book = Book.new
  end
  def index
      @book = Book.new
      @user = current_user
      @books = @user.books
      @users = User.all
  end

  def edit
     @user = User.find(params[:id])
     unless @user.id == current_user.id
     redirect_to user_path(current_user.id)
     else
     @user = User.find(params[:id])
     end
  end

  def update
    @user = User.find(params[:id])
    unless @user.id == current_user.id
    redirect_to user_path(current_user.id)
    end

    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(current_user)
    else
    render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
 <h1>User info</h1>
  <div>
  <%= image_tag user.get_profile_image(100,100) %>
  <P>name : <%= user.name %></P>
  <p>introduction：<%= user.introduction %></p>
  <% if user == current_user %>
    <a><%= link_to edit_user_path(user),class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog" aria-hidden="true"></i></a>
    <% end %>
  <% else %>
    <a><%= link_to edit_user_path(user),class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog" aria-hidden="true"></i></a>
    <% end %>
  <% end %>
 </div>

 <h1>New book</h1>



  <%= form_with model: book do |f| %>
   <div class="text_field">
   <div>Title</div>
   <%= f.text_field :title %>

   <div>Opinion</div>
   <%= f.text_area :body %>
   </div>

   <div class="text-submit"><%= f.submit 'Create Book', class: "btn btn-sm btn-success" %></div>
  <% end %>

app/views/books/edit.html.erb
   <% if @book.errors.any? %>
   <%= @book.errors.count %>errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
   <% end %>


  <%= form_with model: @book do |f| %>
   <div class="container">
   <div class="row">
   <div class="mx-auto">
   <h3>Editing Book</h3>
   <div class="col-md-12">
   <h4>Title</h4>
   <div class="col-md-12">
　 <%= f.text_field :title %>
   </div>
   <div class="col-md-12">
   <h4>Body</h4>
　 <%= f.text_area :body %>
   </div>
   <div class="col-md-12">
　<%= f.submit 'Update Book', class: "btn btn-sm btn-success" %>
   </div>
　<%= link_to "Show", book_path(@book.id) %>|
  <a href="/books">Back</a>
  </div>
  </div>
  </div>
  <% end %>

app/views/books/index.html.erb
 <% if @book.errors.any? %>
   <%= @book.errors.count %>errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>


 <div class="container">
  <div class="row">
   <div class="col-md-3">
    <%= render 'list', book: @book, user: @user %>
   </div>
  <div class="col-md-8 offset-md-1">
   <table class="table">
    <h1>Books</h1>

  <thead>
   <tr>
    <th></th>
    <th>Title</th>
    <th>Introduction</th>
   </tr>
  </thead>

   <tbody>
   <tr><% @books.each do |book| %></tr>
   <td><%= link_to user_path(book.user.id) do %>
   <%= image_tag book.user.get_profile_image(100, 100) %>
   <% end %></td>
   <td><%= link_to book.title,book_path(book.id) %></td>
   <td><%= book.body %></td>
   <% end %>
   </tbody>
   </table>
   </div>
  </div>
 </div>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

 <div class="container">
 <div class="row">
 <div class="col-md-3">
 <%= render 'list', book: @book, user: @user %>
 </div>

 <div class="col-md-8 offset-md-1">



<h1>Book detail</h1>




<table class="table">
<tr>
  <td><%= image_tag @books.user.get_profile_image(100,100) %></td>
  <td><%= link_to @user.name,  user_path(@user.id) %></td>
  <td><%= link_to @books.title, book_path(@books.id) %></td>
  <td><%= @books.body %></td>
  <% if @books.user == current_user %>
  <td><%= link_to "Edit", edit_book_path(@books.id), class: "btn btn-sm btn-success" %></td>
  <td><%= link_to "Destroy", book_path(@books.id), class: "btn btn-sm btn-danger", method: :delete %></td>
  <% end %>
</tr>

</table>

app/views/homes/about.html.erb
 <div class="container">
  <di class="row">
   <h1 class="mx-auto">
     WELCOMETO
   <i class="fas fa-book" aria-hidden="true"></i>
     BOOKERS</h1>
  </div>
 </div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
 <div class="container">
 <di class="row">
 <div class="mx-auto">

  <h1 class="mx-auto"> WELCOMETO
   <i class="fas fa-book" aria-hidden="true"></i>
     BOOKERS</h1>
 <p>you can share and exchange your opinions , inpressions , and emotions

 about various books!</p>

 <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
 <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>

 </div>
 </div>
 </div>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/d1642612f4.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-secondary bg-dark">
      <div class="container">
      <% if user_signed_in? %>

      <a class="navbar-brand p-3 text-light" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <p><%= link_to user_path(current_user.id),class: 'nav-link text-light' do %>
      <i class="fas fa-home" aria-hidden="true"></i>Home</p>
      <% end %>

      </li>

      <li class="nav-item">
      <p><%= link_to users_path,class: 'nav-link text-light' do %>
      <i class="fas fa-users" aria-hidden="true"></i>Users</p>
      <% end %>
      </li>

      <li class="nav-item">
      <p><%= link_to books_path,class: 'nav-link text-light' do %>
      <i class="fas fa-book-open" aria-hidden="true"></i>Books</p>
      <% end %>
      </li>

      <li class="nav-item">
      <p><%= link_to  destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
       <i class="fas fa-sign-out-alt" aria-hidden="true"></i>Log out</p>
      <% end %>
      </li>
      </ul>
      </div>

     <% else %>
      <a class="navbar-brand p-3 text-light" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <a class="nav-link text-light" href="/">
      <i class="fas fa-home" aria-hidden="true"></i>Home</a>
      </li>
      <li class="nav-item">
      <a class="nav-link text-light" href="/home/about">
      <i class="fas fa-link" aria-hidden="true"></i>About</a>
      </li>
      <li class="nav-item">
      <a class="nav-link text-light" href="/users/sign_up">
      <i class="fas fa-user-plus" aria-hidden="true"></i>Sign up</a>
      </li>
      <li class="nav-item">
      <a class="nav-link text-light" href="/users/sign_in">
      <i class="fas fa-sign-in-alt" aria-hidden="true"></i>Log in</a>
      </li>
      <% end %>
      </li>
      </ul>
      </div>
     </div>
     </nav>
    </header>
    <%= yield %>

    <footer>
     <div class="container mt-5">
       <div class="row">
         <div class="mx-auto">
         <p>CopyRight Infratop.inc</p>
         </div>
       </div>
     </div>

    </footer>

  </body>

</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this user from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @user do |f| %>
  <div class="container">
   <div class="row">
   <div class="mx-auto">
  <h2>User info</h2>
  <div class="col-lg-12">
  <label for="inputName">Name</label>
  </div>
  <div class="col-lg-12">
  <%= f.text_field :name, autofocus: true, id:"inputName" %>
  </div>
  <div class="col-lg-12">
  <label for="inputImage">ProfileImage</label>
  </div>
  <div class="col-lg-12">
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  </div>
  <div class="col-lg-12">
  <label for="inputIntroduction">Introduction</label>
  </div>
  <div class="col-lg-12">
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %>
  </div>
  <div class="col-lg-12">
  <%= f.submit "Update User", class: "btn btn-sm btn-success" %>
  </div>
  </div>
  </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
 <div class="col-md-3">
 <%= render 'books/list', book: @book, user: @user %>
 </div>

<div class="col-md-8 offset-md-1">
<table class="table">
 <h1>Users</h1>
 <thead>
  <tr>
   <th></th>
   <th>image</th>
   <th>name</th>
   <th colspan="3"></th>
  </tr>
 </thead>

<tbody>
  <tr><% @users.each do |user| %></tr>
  <td><%= image_tag user.get_profile_image(100,100) %></td>
  <td><%= user.name %></td>
  <td><%= link_to "Show", user_path(user.id) %></td>
  <% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
 <div class="row">
  <div class="col-md-3">
  <%= render 'books/list', book: @book, user: @user %>
  </div>

 <div class="col-md-8 offset-md-1">
 <table class="table">

 <h1>Books</h1>

 <thead>
  <tr>
  <th></th>
  <th>Title</th>
  <th>Intoroduction</th>
  </tr>
 </thead>

<tbody>
 <tr><% @books.each do |book| %></tr>
 <td><%= link_to user_path(book.user.id) do %>
     <%= image_tag book.user.get_profile_image(100, 100) %>
     <% end %></td>
 <td><%= link_to book.title, book_path(book.id)%></td>
 <td><%= book.body%></td>
 <% end %>
</tbody>

</table>
</div>
</div>
</div>